name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: clippy
        override: true

    - name: Install cargo-audit
      run: cargo install cargo-audit
      
    - name: Audit dependencies
      run: cargo audit

    - name: Lint with Clippy
      run: cargo clippy -- -D clippy::unwrap_used

    - name: Check
      run: cargo check --verbose
      
    - name: Test
      run: cargo test --verbose
